--- 场景控制器 非必需，对于一些复杂的场景建议使用，把场景中一些处理挪到这里实现
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yzx.
--- DateTime: 2019/5/30 13:25
--- 使用方法:对应场景如XX场景, 建立XXSceneCtrl 继承BaseSceneCtrl
--- 在XXScene中持有，跟随XXScene生命周期


---@class BattleSceneCtrl:BaseSceneCtrl
local BattleSceneCtrl = BaseClass("BattleSceneCtrl", BaseSceneCtrl)
local base = BaseSceneCtrl

function BattleSceneCtrl:OnCreate()
    base.OnCreate(self)

    ---@type CoBattleScene
    self.scene = self.scene
    Logger.Log(">>>BattleSceneCtrl:OnCreate")
end

function BattleSceneCtrl:OnCompleteEnter()
    base.OnCompleteEnter(self)
    Logger.Log(">>>BattleSceneCtrl:OnCompleteEnter")

end

function BattleSceneCtrl:OnLeave()
    base.OnLeave(self)
    Logger.Log(">>>BattleSceneCtrl:OnLeave")

end

function BattleSceneCtrl:Clear()

end

function BattleSceneCtrl:OnDestroy()
    base.OnDestroy(self)
end

--region local 私有


--endregion

--region 一些监听回调处理


--endregion
return BattleSceneCtrl

