---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yzx.
--- DateTime: 2018/12/29 16:31
---

---提供一些C#端调用Lua的方法

GlobalLuaUtil = {}

--判断窗口是否打开
function GlobalLuaUtil.IsUIWindowShow(pWindowName)
    return SingleGet.UIManager():IsShowing(pWindowName)
end

--打开一个窗口
function GlobalLuaUtil.ShowUIWindow(pWindowName)
    return SingleGet.UIManager():OpenWindow(pWindowName)
end

--关闭一个窗口
function GlobalLuaUtil.CloseUIWindow(pWindowName)
    return SingleGet.UIManager():CloseWindow(pWindowName)
end
