---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yzx.
--- DateTime: 2019/5/28 0:28
---

---@class ConfigManager:Singleton
local ConfigManager = BaseClass("ConfigManager", Singleton)

ConfigManager.__config__table = {}

---Generated start---


---Generated end---

---@return
function ConfigManager:GetCfgServerSevAreaTable()
    ConfigManager.__config__table[]
end


return ConfigManager