---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yzx.
--- DateTime: 2019/5/28 0:28
---

---@class ConfigCfgManager:Singleton
local ConfigCfgManager = BaseClass("ConfigManager", Singleton)

ConfigCfgManager.__config__table = {}

---Generated start---


---Generated end---

---@return CfgServerSevListHelper
function ConfigCfgManager:GetServerSevList()
    return reload("Config.Data.CfgServerSevListTable")
end

---@return CfgServerAreaLangSevAreaHelper
function ConfigCfgManager:GetServerAreaLangSevArea()
    return reload("Config.Data.CfgServerAreaLangSevAreaTable")
end


return ConfigCfgManager