
--- 配置表获取类
--- 注意Auto Generated Start end 之间的为自动生成不要修改
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yzx.
--- DateTime: 2019/5/28 0:28
---

---@class ConfigCfgManager:Singleton
local ConfigCfgManager = BaseClass("ConfigManager", Singleton)

---Auto Generated Start---

---@return Cfgavatar_initdatasHelper
function ConfigCfgManager:Getavatar_initdatas()
	return reload('Config.Data.Cfgavatar_initdatasTable')
end

---@return CfgdialogsdatasHelper
function ConfigCfgManager:Getdialogsdatas()
	return reload('Config.Data.CfgdialogsdatasTable')
end

---@return CfgentitiesdatasHelper
function ConfigCfgManager:Getentitiesdatas()
	return reload('Config.Data.CfgentitiesdatasTable')
end

---@return CfgServerAreaLangSevAreaHelper
function ConfigCfgManager:GetServerAreaLangSevArea()
	return reload('Config.Data.CfgServerAreaLangSevAreaTable')
end

---@return CfgServerSevListHelper
function ConfigCfgManager:GetServerSevList()
	return reload('Config.Data.CfgServerSevListTable')
end

---@return CfgskillsdatasHelper
function ConfigCfgManager:Getskillsdatas()
	return reload('Config.Data.CfgskillsdatasTable')
end

---@return CfgskillseffsdatasHelper
function ConfigCfgManager:Getskillseffsdatas()
	return reload('Config.Data.CfgskillseffsdatasTable')
end

---@return CfgSpacesdatasHelper
function ConfigCfgManager:GetSpacesdatas()
	return reload('Config.Data.CfgSpacesdatasTable')
end

---@return Server
function ConfigCfgManager:Server()
	return reload('Config.Data.Server')
end

---@return ServerAreaLang
function ConfigCfgManager:ServerAreaLang()
	return reload('Config.Data.ServerAreaLang')
end

---@return ServerLang
function ConfigCfgManager:ServerLang()
	return reload('Config.Data.ServerLang')
end
---Auto Generated End---







return ConfigCfgManager